-- database/schema.sql
-- Movies3: Core PostgreSQL schema for IMDb-based personal library

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

-- ===========================
--  Reference tables
-- ===========================

CREATE TABLE country_ref (
    id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    iso2_code   CHAR(2) UNIQUE,
    iso3_code   CHAR(3) UNIQUE
);

CREATE TABLE language_ref (
    id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    iso_code    TEXT NOT NULL UNIQUE
);

CREATE TABLE genre_ref (
    id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE
);

CREATE TABLE certificate_ref (
    id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    description TEXT
);

-- Optional: different certificates per country (e.g. US PG-13 vs UK 12A)
CREATE TABLE certificate_country (
    country_id      SMALLINT NOT NULL,
    certificate_id  SMALLINT NOT NULL,
    min_age         SMALLINT,

    PRIMARY KEY (country_id, certificate_id),

    CONSTRAINT certificate_country_country_fk
        FOREIGN KEY (country_id)
        REFERENCES country_ref (id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT certificate_country_certificate_fk
        FOREIGN KEY (certificate_id)
        REFERENCES certificate_ref (id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE title_type_ref (
    id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,   -- movie, tvSeries, episode, etc.
    is_series   BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE connection_type_ref (
    id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE    -- remake, spin-off, same-universe, etc.
);

CREATE TABLE parental_guide_category_ref (
    id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE    -- violence, nudity, profanity, etc.
);

CREATE TABLE quality_ref (
    id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE    -- 480p, 720p, 1080p, 4K, etc.
);

CREATE TABLE display_ref (
    id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE    -- HDR, SDR, 3D, IMAX, etc.
);

CREATE TABLE cast_role_type_ref (
    id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE    -- actor, director, writer, etc.
);

CREATE TABLE award_event_ref (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE    -- Oscars, Golden Globes, etc.
);

CREATE TABLE award_nomination_type_ref (
    id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE    -- nominated, won, etc.
);

-- ===========================
--  Core entities
-- ===========================

CREATE TABLE person (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imdb_id             TEXT UNIQUE,    -- nconst
    name                TEXT NOT NULL,
    birth_year          SMALLINT,
    death_year          SMALLINT,
    primary_profession  TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE title (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imdb_id             TEXT UNIQUE,    -- tconst
    title_type_id       SMALLINT NOT NULL,
    primary_title       TEXT NOT NULL,
    original_title      TEXT,
    start_year          SMALLINT,
    end_year            SMALLINT,
    runtime_minutes     INTEGER,
    primary_country_id  SMALLINT,
    poster_url          TEXT,
    metacritic_rating   SMALLINT,
    revenue             BIGINT,
    imdb_rating         NUMERIC(4,1),
    imdb_votes          INTEGER,
    popularity          BIGINT,
    parent_title_id     INTEGER,
    season_number       INTEGER,
    episode_number      INTEGER,
    total_seasons       INTEGER,
    total_episodes      INTEGER,
    date_released       DATE,

    date_added          TIMESTAMPTZ NOT NULL DEFAULT now(),
    date_updated        TIMESTAMPTZ NOT NULL DEFAULT now(),

    is_adult            BOOLEAN NOT NULL DEFAULT FALSE,
    is_available        BOOLEAN NOT NULL DEFAULT FALSE,

    viewed_count        BIGINT NOT NULL DEFAULT 0,
    played_count        BIGINT NOT NULL DEFAULT 0,
    liked_count         BIGINT NOT NULL DEFAULT 0,
    disliked_count      BIGINT NOT NULL DEFAULT 0,
    last_watched_at     TIMESTAMPTZ,
    user_rating         SMALLINT,
    user_notes          TEXT,

    folder_name         TEXT,
    folder_path         TEXT,

    CONSTRAINT title_title_type_fk
        FOREIGN KEY (title_type_id)
        REFERENCES title_type_ref (id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    CONSTRAINT title_primary_country_fk
        FOREIGN KEY (primary_country_id)
        REFERENCES country_ref (id)
        ON UPDATE CASCADE ON DELETE SET NULL,

    CONSTRAINT title_parent_title_fk
        FOREIGN KEY (parent_title_id)
        REFERENCES title (id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

-- ===========================
--  Title attributes / junctions
-- ===========================

CREATE TABLE title_alias (
    title_id    INTEGER NOT NULL,
    alias       TEXT NOT NULL,

    PRIMARY KEY (title_id, alias),

    CONSTRAINT title_alias_title_fk
        FOREIGN KEY (title_id)
        REFERENCES title (id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE title_country (
    title_id    INTEGER NOT NULL,
    country_id  SMALLINT NOT NULL,

    PRIMARY KEY (title_id, country_id),

    CONSTRAINT title_country_title_fk
        FOREIGN KEY (title_id)
        REFERENCES title (id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT title_country_country_fk
        FOREIGN KEY (country_id)
        REFERENCES country_ref (id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE title_language (
    title_id    INTEGER NOT NULL,
    language_id SMALLINT NOT NULL,
    is_original BOOLEAN NOT NULL DEFAULT FALSE,

    PRIMARY KEY (title_id, language_id),

    CONSTRAINT title_language_title_fk
        FOREIGN KEY (title_id)
        REFERENCES title (id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT title_language_language_fk
        FOREIGN KEY (language_id)
        REFERENCES language_ref (id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE title_genre (
    title_id    INTEGER NOT NULL,
    genre_id    SMALLINT NOT NULL,

    PRIMARY KEY (title_id, genre_id),

    CONSTRAINT title_genre_title_fk
        FOREIGN KEY (title_id)
        REFERENCES title (id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT title_genre_genre_fk
        FOREIGN KEY (genre_id)
        REFERENCES genre_ref (id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE title_certificate (
    title_id        INTEGER NOT NULL,
    certificate_id  SMALLINT NOT NULL,
    country_id      SMALLINT,

    PRIMARY KEY (title_id, certificate_id, country_id),

    CONSTRAINT title_certificate_title_fk
        FOREIGN KEY (title_id)
        REFERENCES title (id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT title_certificate_certificate_fk
        FOREIGN KEY (certificate_id)
        REFERENCES certificate_ref (id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT title_certificate_country_fk
        FOREIGN KEY (country_id)
        REFERENCES country_ref (id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE title_cast (
    title_id        INTEGER NOT NULL,
    person_id       BIGINT NOT NULL,
    role_type_id    SMALLINT NOT NULL,
    character_name  TEXT,
    billing_order   INTEGER,
    is_guest        BOOLEAN NOT NULL DEFAULT FALSE,
    is_voice        BOOLEAN NOT NULL DEFAULT FALSE,

    PRIMARY KEY (title_id, person_id, role_type_id),

    CONSTRAINT title_cast_title_fk
        FOREIGN KEY (title_id)
        REFERENCES title (id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT title_cast_person_fk
        FOREIGN KEY (person_id)
        REFERENCES person (id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT title_cast_role_type_fk
        FOREIGN KEY (role_type_id)
        REFERENCES cast_role_type_ref (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE title_connection (
    title_id            INTEGER NOT NULL,
    other_title_id      INTEGER NOT NULL,
    connection_type_id  SMALLINT NOT NULL,
    notes               TEXT,

    PRIMARY KEY (title_id, other_title_id, connection_type_id),

    CONSTRAINT title_connection_title_fk
        FOREIGN KEY (title_id)
        REFERENCES title (id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT title_connection_other_title_fk
        FOREIGN KEY (other_title_id)
        REFERENCES title (id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT title_connection_type_fk
        FOREIGN KEY (connection_type_id)
        REFERENCES connection_type_ref (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE title_parental_guide (
    title_id        INTEGER NOT NULL,
    category_id     SMALLINT NOT NULL,
    severity        SMALLINT NOT NULL,   -- e.g. 0–4
    description     TEXT,

    PRIMARY KEY (title_id, category_id),

    CONSTRAINT title_pg_title_fk
        FOREIGN KEY (title_id)
        REFERENCES title (id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT title_pg_category_fk
        FOREIGN KEY (category_id)
        REFERENCES parental_guide_category_ref (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE title_award (
    title_id            INTEGER NOT NULL,
    person_id           BIGINT NOT NULL,
    event_id            INTEGER NOT NULL,
    nomination_type_id  SMALLINT NOT NULL,
    award_year          INTEGER,
    description         TEXT,
    category            TEXT,

    PRIMARY KEY (title_id, person_id, event_id, nomination_type_id, award_year, category),

    CONSTRAINT title_award_title_fk
        FOREIGN KEY (title_id)
        REFERENCES title (id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT title_award_person_fk
        FOREIGN KEY (person_id)
        REFERENCES person (id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT title_award_event_fk
        FOREIGN KEY (event_id)
        REFERENCES award_event_ref (id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT title_award_nomination_type_fk
        FOREIGN KEY (nomination_type_id)
        REFERENCES award_nomination_type_ref (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

-- ===========================
--  File / media layer
-- ===========================

CREATE TABLE media_file (
    id                      BIGSERIAL PRIMARY KEY,
    title_id                INTEGER NOT NULL,
    quality_id              SMALLINT,
    display_id              SMALLINT,
    file_path               TEXT NOT NULL,
    file_size_bytes         BIGINT,
    audio_language_id       SMALLINT,
    subtitle_language_id    SMALLINT,
    is_missing              BOOLEAN NOT NULL DEFAULT FALSE,
    last_checked_at         TIMESTAMPTZ,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT media_file_title_fk
        FOREIGN KEY (title_id)
        REFERENCES title (id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT media_file_quality_fk
        FOREIGN KEY (quality_id)
        REFERENCES quality_ref (id)
        ON UPDATE CASCADE ON DELETE SET NULL,

    CONSTRAINT media_file_display_fk
        FOREIGN KEY (display_id)
        REFERENCES display_ref (id)
        ON UPDATE CASCADE ON DELETE SET NULL,

    CONSTRAINT media_file_audio_lang_fk
        FOREIGN KEY (audio_language_id)
        REFERENCES language_ref (id)
        ON UPDATE CASCADE ON DELETE SET NULL,

    CONSTRAINT media_file_sub_lang_fk
        FOREIGN KEY (subtitle_language_id)
        REFERENCES language_ref (id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

-- ===========================
--  Tags and requests
-- ===========================

CREATE TABLE tag (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    TEXT NOT NULL UNIQUE       -- e.g. "Maryam", "Family", "Oscar Winner"
);

CREATE TABLE title_tag (
    title_id    INTEGER NOT NULL,
    tag_id      INTEGER NOT NULL,

    PRIMARY KEY (title_id, tag_id),

    CONSTRAINT title_tag_title_fk
        FOREIGN KEY (title_id)
        REFERENCES title (id)
        ON UPDATE CASCADE ON DELETE CASCADE,

    CONSTRAINT title_tag_tag_fk
        FOREIGN KEY (tag_id)
        REFERENCES tag (id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE requested_title (
    id              BIGSERIAL PRIMARY KEY,
    imdb_id         TEXT,
    title_name      TEXT,
    requested_by    TEXT,
    requested_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    notes           TEXT
);

CREATE TABLE not_downloaded_title (
    id              BIGSERIAL PRIMARY KEY,
    imdb_id         TEXT,
    title_name      TEXT,
    reason          TEXT,
    last_checked_at TIMESTAMPTZ
);

-- ===========================
--  Indexes for search
-- ===========================

CREATE INDEX idx_title_primary_title_lower
    ON title (LOWER(primary_title));

CREATE INDEX idx_title_original_title_lower
    ON title (LOWER(original_title));

CREATE INDEX idx_title_imdb_id
    ON title (imdb_id);

CREATE INDEX idx_title_available_popularity
    ON title (is_available, popularity DESC);

CREATE INDEX idx_title_date_added
    ON title (date_added DESC);

CREATE INDEX idx_media_file_title
    ON media_file (title_id);

CREATE INDEX idx_person_name_lower
    ON person (LOWER(name));
